### ISSUE TITLE
Intermittent error: claim "ref_protected" does not match any associated bound claim values

### ISSUE THREAD

**Issue by hiaik** [hashicorp/vault-plugin-auth-jwt#305]
Hi Team,

We are on 1.7.1 (https://github.com/hashicorp/vault/blob/main/CHANGELOG-pre-v1.10.md#171) which uses github.com/hashicorp/vault-plugin-auth-jwt v0.9.3

We experience intermittent error "claim "ref_protected" does not match any associated bound claim values" which disappears itself with unknown to us conditions.

It seems coming from:
https://github.com/hashicorp/vault-plugin-auth-jwt/blob/cb729ddbd4ba4b5199345dab1c43448a64b10567/claims.go#L138

Role yaml file is:
```yaml
---
name: app-ci
role_type: jwt
token_policies:
  - app-ci
  - gitlab-runner
token_explicit_max_ttl: 60
user_claim: user_email
bound_claims:
  project_path: <project path in gitlab>
  iss:
    - https://<gitlab url>
    - <gitlab url>
bound_claims_type: string
```

I have checked both changelogs:
* https://github.com/hashicorp/vault-plugin-auth-jwt/blob/main/CHANGELOG.md
* https://github.com/hashicorp/vault/blob/main/CHANGELOG.md

Have not found any related issue. 

Still this issue is intermittent on our side. It occurs for pipeline jobs on protected tags / branches. And it disappears itself with no known changes on your side.

Could you please share any guidance?
